/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthSignInLayoutRouteImport } from './pages/_auth/_sign-in/layout'
import { Route as AppPanelLayoutRouteImport } from './pages/_app/panel/layout'
import { Route as AuthSignInIndexRouteImport } from './pages/_auth/_sign-in/index'
import { Route as AppPanelIndexRouteImport } from './pages/_app/panel/index'
import { Route as AppPanelOverviewIndexRouteImport } from './pages/_app/panel/overview/index'

const AuthSignInLayoutRoute = AuthSignInLayoutRouteImport.update({
  id: '/_auth/_sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPanelLayoutRoute = AppPanelLayoutRouteImport.update({
  id: '/_app/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignInLayoutRoute,
} as any)
const AppPanelIndexRoute = AppPanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPanelLayoutRoute,
} as any)
const AppPanelOverviewIndexRoute = AppPanelOverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => AppPanelLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/panel': typeof AppPanelLayoutRouteWithChildren
  '/': typeof AuthSignInIndexRoute
  '/panel/': typeof AppPanelIndexRoute
  '/panel/overview/': typeof AppPanelOverviewIndexRoute
}
export interface FileRoutesByTo {
  '/panel': typeof AppPanelIndexRoute
  '/': typeof AuthSignInIndexRoute
  '/panel/overview': typeof AppPanelOverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/panel': typeof AppPanelLayoutRouteWithChildren
  '/_auth/_sign-in': typeof AuthSignInLayoutRouteWithChildren
  '/_app/panel/': typeof AppPanelIndexRoute
  '/_auth/_sign-in/': typeof AuthSignInIndexRoute
  '/_app/panel/overview/': typeof AppPanelOverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/panel' | '/' | '/panel/' | '/panel/overview/'
  fileRoutesByTo: FileRoutesByTo
  to: '/panel' | '/' | '/panel/overview'
  id:
    | '__root__'
    | '/_app/panel'
    | '/_auth/_sign-in'
    | '/_app/panel/'
    | '/_auth/_sign-in/'
    | '/_app/panel/overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppPanelLayoutRoute: typeof AppPanelLayoutRouteWithChildren
  AuthSignInLayoutRoute: typeof AuthSignInLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth/_sign-in': {
      id: '/_auth/_sign-in'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthSignInLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/panel': {
      id: '/_app/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AppPanelLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_sign-in/': {
      id: '/_auth/_sign-in/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthSignInLayoutRoute
    }
    '/_app/panel/': {
      id: '/_app/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof AppPanelIndexRouteImport
      parentRoute: typeof AppPanelLayoutRoute
    }
    '/_app/panel/overview/': {
      id: '/_app/panel/overview/'
      path: '/overview'
      fullPath: '/panel/overview/'
      preLoaderRoute: typeof AppPanelOverviewIndexRouteImport
      parentRoute: typeof AppPanelLayoutRoute
    }
  }
}

interface AppPanelLayoutRouteChildren {
  AppPanelIndexRoute: typeof AppPanelIndexRoute
  AppPanelOverviewIndexRoute: typeof AppPanelOverviewIndexRoute
}

const AppPanelLayoutRouteChildren: AppPanelLayoutRouteChildren = {
  AppPanelIndexRoute: AppPanelIndexRoute,
  AppPanelOverviewIndexRoute: AppPanelOverviewIndexRoute,
}

const AppPanelLayoutRouteWithChildren = AppPanelLayoutRoute._addFileChildren(
  AppPanelLayoutRouteChildren,
)

interface AuthSignInLayoutRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthSignInLayoutRouteChildren: AuthSignInLayoutRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthSignInLayoutRouteWithChildren =
  AuthSignInLayoutRoute._addFileChildren(AuthSignInLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppPanelLayoutRoute: AppPanelLayoutRouteWithChildren,
  AuthSignInLayoutRoute: AuthSignInLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
