/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthSignInLayoutRouteImport } from './pages/_auth/_sign-in/layout'
import { Route as AppPanelLayoutRouteImport } from './pages/_app/panel/layout'
import { Route as AuthSignInIndexRouteImport } from './pages/_auth/_sign-in/index'
import { Route as AppPanelIndexRouteImport } from './pages/_app/panel/index'
import { Route as AppPanelValidationIndexRouteImport } from './pages/_app/panel/validation/index'
import { Route as AppPanelOverviewIndexRouteImport } from './pages/_app/panel/overview/index'
import { Route as AppPanelValidationCompanyIdIndexRouteImport } from './pages/_app/panel/validation/$companyId/index'

const AuthSignInLayoutRoute = AuthSignInLayoutRouteImport.update({
  id: '/_auth/_sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPanelLayoutRoute = AppPanelLayoutRouteImport.update({
  id: '/_app/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignInLayoutRoute,
} as any)
const AppPanelIndexRoute = AppPanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPanelLayoutRoute,
} as any)
const AppPanelValidationIndexRoute = AppPanelValidationIndexRouteImport.update({
  id: '/validation/',
  path: '/validation/',
  getParentRoute: () => AppPanelLayoutRoute,
} as any)
const AppPanelOverviewIndexRoute = AppPanelOverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => AppPanelLayoutRoute,
} as any)
const AppPanelValidationCompanyIdIndexRoute =
  AppPanelValidationCompanyIdIndexRouteImport.update({
    id: '/validation/$companyId/',
    path: '/validation/$companyId/',
    getParentRoute: () => AppPanelLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/panel': typeof AppPanelLayoutRouteWithChildren
  '/': typeof AuthSignInIndexRoute
  '/panel/': typeof AppPanelIndexRoute
  '/panel/overview/': typeof AppPanelOverviewIndexRoute
  '/panel/validation/': typeof AppPanelValidationIndexRoute
  '/panel/validation/$companyId/': typeof AppPanelValidationCompanyIdIndexRoute
}
export interface FileRoutesByTo {
  '/panel': typeof AppPanelIndexRoute
  '/': typeof AuthSignInIndexRoute
  '/panel/overview': typeof AppPanelOverviewIndexRoute
  '/panel/validation': typeof AppPanelValidationIndexRoute
  '/panel/validation/$companyId': typeof AppPanelValidationCompanyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/panel': typeof AppPanelLayoutRouteWithChildren
  '/_auth/_sign-in': typeof AuthSignInLayoutRouteWithChildren
  '/_app/panel/': typeof AppPanelIndexRoute
  '/_auth/_sign-in/': typeof AuthSignInIndexRoute
  '/_app/panel/overview/': typeof AppPanelOverviewIndexRoute
  '/_app/panel/validation/': typeof AppPanelValidationIndexRoute
  '/_app/panel/validation/$companyId/': typeof AppPanelValidationCompanyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/panel'
    | '/'
    | '/panel/'
    | '/panel/overview/'
    | '/panel/validation/'
    | '/panel/validation/$companyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/panel'
    | '/'
    | '/panel/overview'
    | '/panel/validation'
    | '/panel/validation/$companyId'
  id:
    | '__root__'
    | '/_app/panel'
    | '/_auth/_sign-in'
    | '/_app/panel/'
    | '/_auth/_sign-in/'
    | '/_app/panel/overview/'
    | '/_app/panel/validation/'
    | '/_app/panel/validation/$companyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppPanelLayoutRoute: typeof AppPanelLayoutRouteWithChildren
  AuthSignInLayoutRoute: typeof AuthSignInLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth/_sign-in': {
      id: '/_auth/_sign-in'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthSignInLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/panel': {
      id: '/_app/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AppPanelLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_sign-in/': {
      id: '/_auth/_sign-in/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthSignInLayoutRoute
    }
    '/_app/panel/': {
      id: '/_app/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof AppPanelIndexRouteImport
      parentRoute: typeof AppPanelLayoutRoute
    }
    '/_app/panel/validation/': {
      id: '/_app/panel/validation/'
      path: '/validation'
      fullPath: '/panel/validation/'
      preLoaderRoute: typeof AppPanelValidationIndexRouteImport
      parentRoute: typeof AppPanelLayoutRoute
    }
    '/_app/panel/overview/': {
      id: '/_app/panel/overview/'
      path: '/overview'
      fullPath: '/panel/overview/'
      preLoaderRoute: typeof AppPanelOverviewIndexRouteImport
      parentRoute: typeof AppPanelLayoutRoute
    }
    '/_app/panel/validation/$companyId/': {
      id: '/_app/panel/validation/$companyId/'
      path: '/validation/$companyId'
      fullPath: '/panel/validation/$companyId/'
      preLoaderRoute: typeof AppPanelValidationCompanyIdIndexRouteImport
      parentRoute: typeof AppPanelLayoutRoute
    }
  }
}

interface AppPanelLayoutRouteChildren {
  AppPanelIndexRoute: typeof AppPanelIndexRoute
  AppPanelOverviewIndexRoute: typeof AppPanelOverviewIndexRoute
  AppPanelValidationIndexRoute: typeof AppPanelValidationIndexRoute
  AppPanelValidationCompanyIdIndexRoute: typeof AppPanelValidationCompanyIdIndexRoute
}

const AppPanelLayoutRouteChildren: AppPanelLayoutRouteChildren = {
  AppPanelIndexRoute: AppPanelIndexRoute,
  AppPanelOverviewIndexRoute: AppPanelOverviewIndexRoute,
  AppPanelValidationIndexRoute: AppPanelValidationIndexRoute,
  AppPanelValidationCompanyIdIndexRoute: AppPanelValidationCompanyIdIndexRoute,
}

const AppPanelLayoutRouteWithChildren = AppPanelLayoutRoute._addFileChildren(
  AppPanelLayoutRouteChildren,
)

interface AuthSignInLayoutRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthSignInLayoutRouteChildren: AuthSignInLayoutRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthSignInLayoutRouteWithChildren =
  AuthSignInLayoutRoute._addFileChildren(AuthSignInLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppPanelLayoutRoute: AppPanelLayoutRouteWithChildren,
  AuthSignInLayoutRoute: AuthSignInLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
