/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PublicLayoutRouteImport } from './pages/_public/layout'
import { Route as PublicIndexRouteImport } from './pages/_public/index'
import { Route as ErrorNotFoundIndexRouteImport } from './pages/_error/not-found/index'
import { Route as AuthSignInIndexRouteImport } from './pages/_auth/sign-in/index'

const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const ErrorNotFoundIndexRoute = ErrorNotFoundIndexRouteImport.update({
  id: '/_error/not-found/',
  path: '/not-found/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/_auth/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/sign-in/': typeof AuthSignInIndexRoute
  '/not-found/': typeof ErrorNotFoundIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/not-found': typeof ErrorNotFoundIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicLayoutRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_error/not-found/': typeof ErrorNotFoundIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in/' | '/not-found/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/not-found'
  id:
    | '__root__'
    | '/_public'
    | '/_public/'
    | '/_auth/sign-in/'
    | '/_error/not-found/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  ErrorNotFoundIndexRoute: typeof ErrorNotFoundIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_error/not-found/': {
      id: '/_error/not-found/'
      path: '/not-found'
      fullPath: '/not-found/'
      preLoaderRoute: typeof ErrorNotFoundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicLayoutRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  ErrorNotFoundIndexRoute: ErrorNotFoundIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
