/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PublicLayoutRouteImport } from './pages/_public/layout'
import { Route as PublicIndexRouteImport } from './pages/_public/index'
import { Route as AuthSignUpLayoutRouteImport } from './pages/_auth/sign-up/layout'
import { Route as AuthSignInLayoutRouteImport } from './pages/_auth/sign-in/layout'
import { Route as ErrorNotFoundIndexRouteImport } from './pages/_error/not-found/index'
import { Route as AuthSignUpIndexRouteImport } from './pages/_auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './pages/_auth/sign-in/index'
import { Route as AppClientMyAccountIndexRouteImport } from './pages/app/_client/my-account/index'
import { Route as PublicnoAuthenticationServicesIndexRouteImport } from './pages/_public/_(no-authentication)/services/index'
import { Route as PublicnoAuthenticationHelpCenterIndexRouteImport } from './pages/_public/_(no-authentication)/help-center/index'
import { Route as AppCompanyorganizationSetCompanySlugLayoutRouteImport } from './pages/app/_company/_(organization-set)/$companySlug/layout'
import { Route as AppCompanyorganizationSetCompanySlugIndexRouteImport } from './pages/app/_company/_(organization-set)/$companySlug/index'
import { Route as PublicnoAuthenticationHelpCenterCompaniesIndexRouteImport } from './pages/_public/_(no-authentication)/help-center/companies/index'
import { Route as AppCompanynoOrganizationSetChar126SettingsIndexRouteImport } from './pages/app/_company/_(no-organization-set)/~/settings/index'

const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const AuthSignUpLayoutRoute = AuthSignUpLayoutRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInLayoutRoute = AuthSignInLayoutRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorNotFoundIndexRoute = ErrorNotFoundIndexRouteImport.update({
  id: '/_error/not-found/',
  path: '/not-found/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignUpLayoutRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignInLayoutRoute,
} as any)
const AppClientMyAccountIndexRoute = AppClientMyAccountIndexRouteImport.update({
  id: '/app/_client/my-account/',
  path: '/app/my-account/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicnoAuthenticationServicesIndexRoute =
  PublicnoAuthenticationServicesIndexRouteImport.update({
    id: '/_(no-authentication)/services/',
    path: '/services/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const PublicnoAuthenticationHelpCenterIndexRoute =
  PublicnoAuthenticationHelpCenterIndexRouteImport.update({
    id: '/_(no-authentication)/help-center/',
    path: '/help-center/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const AppCompanyorganizationSetCompanySlugLayoutRoute =
  AppCompanyorganizationSetCompanySlugLayoutRouteImport.update({
    id: '/app/_company/_(organization-set)/$companySlug',
    path: '/app/$companySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCompanyorganizationSetCompanySlugIndexRoute =
  AppCompanyorganizationSetCompanySlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCompanyorganizationSetCompanySlugLayoutRoute,
  } as any)
const PublicnoAuthenticationHelpCenterCompaniesIndexRoute =
  PublicnoAuthenticationHelpCenterCompaniesIndexRouteImport.update({
    id: '/_(no-authentication)/help-center/companies/',
    path: '/help-center/companies/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const AppCompanynoOrganizationSetChar126SettingsIndexRoute =
  AppCompanynoOrganizationSetChar126SettingsIndexRouteImport.update({
    id: '/app/_company/_(no-organization-set)/~/settings/',
    path: '/app/~/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/sign-in': typeof AuthSignInLayoutRouteWithChildren
  '/sign-up': typeof AuthSignUpLayoutRouteWithChildren
  '/sign-in/': typeof AuthSignInIndexRoute
  '/sign-up/': typeof AuthSignUpIndexRoute
  '/not-found/': typeof ErrorNotFoundIndexRoute
  '/app/$companySlug': typeof AppCompanyorganizationSetCompanySlugLayoutRouteWithChildren
  '/help-center/': typeof PublicnoAuthenticationHelpCenterIndexRoute
  '/services/': typeof PublicnoAuthenticationServicesIndexRoute
  '/app/my-account/': typeof AppClientMyAccountIndexRoute
  '/help-center/companies/': typeof PublicnoAuthenticationHelpCenterCompaniesIndexRoute
  '/app/$companySlug/': typeof AppCompanyorganizationSetCompanySlugIndexRoute
  '/app/~/settings/': typeof AppCompanynoOrganizationSetChar126SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
  '/not-found': typeof ErrorNotFoundIndexRoute
  '/help-center': typeof PublicnoAuthenticationHelpCenterIndexRoute
  '/services': typeof PublicnoAuthenticationServicesIndexRoute
  '/app/my-account': typeof AppClientMyAccountIndexRoute
  '/help-center/companies': typeof PublicnoAuthenticationHelpCenterCompaniesIndexRoute
  '/app/$companySlug': typeof AppCompanyorganizationSetCompanySlugIndexRoute
  '/app/~/settings': typeof AppCompanynoOrganizationSetChar126SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicLayoutRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInLayoutRouteWithChildren
  '/_auth/sign-up': typeof AuthSignUpLayoutRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_error/not-found/': typeof ErrorNotFoundIndexRoute
  '/app/_company/_(organization-set)/$companySlug': typeof AppCompanyorganizationSetCompanySlugLayoutRouteWithChildren
  '/_public/_(no-authentication)/help-center/': typeof PublicnoAuthenticationHelpCenterIndexRoute
  '/_public/_(no-authentication)/services/': typeof PublicnoAuthenticationServicesIndexRoute
  '/app/_client/my-account/': typeof AppClientMyAccountIndexRoute
  '/_public/_(no-authentication)/help-center/companies/': typeof PublicnoAuthenticationHelpCenterCompaniesIndexRoute
  '/app/_company/_(organization-set)/$companySlug/': typeof AppCompanyorganizationSetCompanySlugIndexRoute
  '/app/_company/_(no-organization-set)/~/settings/': typeof AppCompanynoOrganizationSetChar126SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/sign-in/'
    | '/sign-up/'
    | '/not-found/'
    | '/app/$companySlug'
    | '/help-center/'
    | '/services/'
    | '/app/my-account/'
    | '/help-center/companies/'
    | '/app/$companySlug/'
    | '/app/~/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/not-found'
    | '/help-center'
    | '/services'
    | '/app/my-account'
    | '/help-center/companies'
    | '/app/$companySlug'
    | '/app/~/settings'
  id:
    | '__root__'
    | '/_public'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_public/'
    | '/_auth/sign-in/'
    | '/_auth/sign-up/'
    | '/_error/not-found/'
    | '/app/_company/_(organization-set)/$companySlug'
    | '/_public/_(no-authentication)/help-center/'
    | '/_public/_(no-authentication)/services/'
    | '/app/_client/my-account/'
    | '/_public/_(no-authentication)/help-center/companies/'
    | '/app/_company/_(organization-set)/$companySlug/'
    | '/app/_company/_(no-organization-set)/~/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  AuthSignInLayoutRoute: typeof AuthSignInLayoutRouteWithChildren
  AuthSignUpLayoutRoute: typeof AuthSignUpLayoutRouteWithChildren
  ErrorNotFoundIndexRoute: typeof ErrorNotFoundIndexRoute
  AppCompanyorganizationSetCompanySlugLayoutRoute: typeof AppCompanyorganizationSetCompanySlugLayoutRouteWithChildren
  AppClientMyAccountIndexRoute: typeof AppClientMyAccountIndexRoute
  AppCompanynoOrganizationSetChar126SettingsIndexRoute: typeof AppCompanynoOrganizationSetChar126SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_error/not-found/': {
      id: '/_error/not-found/'
      path: '/not-found'
      fullPath: '/not-found/'
      preLoaderRoute: typeof ErrorNotFoundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthSignUpLayoutRoute
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthSignInLayoutRoute
    }
    '/app/_client/my-account/': {
      id: '/app/_client/my-account/'
      path: '/app/my-account'
      fullPath: '/app/my-account/'
      preLoaderRoute: typeof AppClientMyAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_(no-authentication)/services/': {
      id: '/_public/_(no-authentication)/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof PublicnoAuthenticationServicesIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/_(no-authentication)/help-center/': {
      id: '/_public/_(no-authentication)/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof PublicnoAuthenticationHelpCenterIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/app/_company/_(organization-set)/$companySlug': {
      id: '/app/_company/_(organization-set)/$companySlug'
      path: '/app/$companySlug'
      fullPath: '/app/$companySlug'
      preLoaderRoute: typeof AppCompanyorganizationSetCompanySlugLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_company/_(organization-set)/$companySlug/': {
      id: '/app/_company/_(organization-set)/$companySlug/'
      path: '/'
      fullPath: '/app/$companySlug/'
      preLoaderRoute: typeof AppCompanyorganizationSetCompanySlugIndexRouteImport
      parentRoute: typeof AppCompanyorganizationSetCompanySlugLayoutRoute
    }
    '/_public/_(no-authentication)/help-center/companies/': {
      id: '/_public/_(no-authentication)/help-center/companies/'
      path: '/help-center/companies'
      fullPath: '/help-center/companies/'
      preLoaderRoute: typeof PublicnoAuthenticationHelpCenterCompaniesIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/app/_company/_(no-organization-set)/~/settings/': {
      id: '/app/_company/_(no-organization-set)/~/settings/'
      path: '/app/~/settings'
      fullPath: '/app/~/settings/'
      preLoaderRoute: typeof AppCompanynoOrganizationSetChar126SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicLayoutRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicnoAuthenticationHelpCenterIndexRoute: typeof PublicnoAuthenticationHelpCenterIndexRoute
  PublicnoAuthenticationServicesIndexRoute: typeof PublicnoAuthenticationServicesIndexRoute
  PublicnoAuthenticationHelpCenterCompaniesIndexRoute: typeof PublicnoAuthenticationHelpCenterCompaniesIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicnoAuthenticationHelpCenterIndexRoute:
    PublicnoAuthenticationHelpCenterIndexRoute,
  PublicnoAuthenticationServicesIndexRoute:
    PublicnoAuthenticationServicesIndexRoute,
  PublicnoAuthenticationHelpCenterCompaniesIndexRoute:
    PublicnoAuthenticationHelpCenterCompaniesIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface AuthSignInLayoutRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthSignInLayoutRouteChildren: AuthSignInLayoutRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthSignInLayoutRouteWithChildren =
  AuthSignInLayoutRoute._addFileChildren(AuthSignInLayoutRouteChildren)

interface AuthSignUpLayoutRouteChildren {
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthSignUpLayoutRouteChildren: AuthSignUpLayoutRouteChildren = {
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthSignUpLayoutRouteWithChildren =
  AuthSignUpLayoutRoute._addFileChildren(AuthSignUpLayoutRouteChildren)

interface AppCompanyorganizationSetCompanySlugLayoutRouteChildren {
  AppCompanyorganizationSetCompanySlugIndexRoute: typeof AppCompanyorganizationSetCompanySlugIndexRoute
}

const AppCompanyorganizationSetCompanySlugLayoutRouteChildren: AppCompanyorganizationSetCompanySlugLayoutRouteChildren =
  {
    AppCompanyorganizationSetCompanySlugIndexRoute:
      AppCompanyorganizationSetCompanySlugIndexRoute,
  }

const AppCompanyorganizationSetCompanySlugLayoutRouteWithChildren =
  AppCompanyorganizationSetCompanySlugLayoutRoute._addFileChildren(
    AppCompanyorganizationSetCompanySlugLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  AuthSignInLayoutRoute: AuthSignInLayoutRouteWithChildren,
  AuthSignUpLayoutRoute: AuthSignUpLayoutRouteWithChildren,
  ErrorNotFoundIndexRoute: ErrorNotFoundIndexRoute,
  AppCompanyorganizationSetCompanySlugLayoutRoute:
    AppCompanyorganizationSetCompanySlugLayoutRouteWithChildren,
  AppClientMyAccountIndexRoute: AppClientMyAccountIndexRoute,
  AppCompanynoOrganizationSetChar126SettingsIndexRoute:
    AppCompanynoOrganizationSetChar126SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
