/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PublicLayoutRouteImport } from './pages/_public/layout'
import { Route as PublicIndexRouteImport } from './pages/_public/index'
import { Route as AuthSignUpLayoutRouteImport } from './pages/_auth/sign-up/layout'
import { Route as AuthSignInLayoutRouteImport } from './pages/_auth/sign-in/layout'
import { Route as PublicServicesIndexRouteImport } from './pages/_public/services/index'
import { Route as ErrorNotFoundIndexRouteImport } from './pages/_error/not-found/index'
import { Route as AuthSignUpIndexRouteImport } from './pages/_auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './pages/_auth/sign-in/index'
import { Route as PublicGeneralFrequentQuestionsIndexRouteImport } from './pages/_public/_general/frequent-questions/index'
import { Route as AppCompanyorganizationSetCompanySlugLayoutRouteImport } from './pages/app/_company/_(organization-set)/$companySlug/layout'
import { Route as AppCompanyorganizationSetCompanySlugIndexRouteImport } from './pages/app/_company/_(organization-set)/$companySlug/index'
import { Route as PublicGeneralFrequentQuestionsCompaniesIndexRouteImport } from './pages/_public/_general/frequent-questions/companies/index'
import { Route as AppCompanynoOrganizationSetChar126SettingsIndexRouteImport } from './pages/app/_company/_(no-organization-set)/~/settings/index'

const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const AuthSignUpLayoutRoute = AuthSignUpLayoutRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInLayoutRoute = AuthSignInLayoutRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicServicesIndexRoute = PublicServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const ErrorNotFoundIndexRoute = ErrorNotFoundIndexRouteImport.update({
  id: '/_error/not-found/',
  path: '/not-found/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignUpLayoutRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignInLayoutRoute,
} as any)
const PublicGeneralFrequentQuestionsIndexRoute =
  PublicGeneralFrequentQuestionsIndexRouteImport.update({
    id: '/_general/frequent-questions/',
    path: '/frequent-questions/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const AppCompanyorganizationSetCompanySlugLayoutRoute =
  AppCompanyorganizationSetCompanySlugLayoutRouteImport.update({
    id: '/app/_company/_(organization-set)/$companySlug',
    path: '/app/$companySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCompanyorganizationSetCompanySlugIndexRoute =
  AppCompanyorganizationSetCompanySlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCompanyorganizationSetCompanySlugLayoutRoute,
  } as any)
const PublicGeneralFrequentQuestionsCompaniesIndexRoute =
  PublicGeneralFrequentQuestionsCompaniesIndexRouteImport.update({
    id: '/_general/frequent-questions/companies/',
    path: '/frequent-questions/companies/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const AppCompanynoOrganizationSetChar126SettingsIndexRoute =
  AppCompanynoOrganizationSetChar126SettingsIndexRouteImport.update({
    id: '/app/_company/_(no-organization-set)/~/settings/',
    path: '/app/~/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/sign-in': typeof AuthSignInLayoutRouteWithChildren
  '/sign-up': typeof AuthSignUpLayoutRouteWithChildren
  '/sign-in/': typeof AuthSignInIndexRoute
  '/sign-up/': typeof AuthSignUpIndexRoute
  '/not-found/': typeof ErrorNotFoundIndexRoute
  '/services/': typeof PublicServicesIndexRoute
  '/app/$companySlug': typeof AppCompanyorganizationSetCompanySlugLayoutRouteWithChildren
  '/frequent-questions/': typeof PublicGeneralFrequentQuestionsIndexRoute
  '/frequent-questions/companies/': typeof PublicGeneralFrequentQuestionsCompaniesIndexRoute
  '/app/$companySlug/': typeof AppCompanyorganizationSetCompanySlugIndexRoute
  '/app/~/settings/': typeof AppCompanynoOrganizationSetChar126SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
  '/not-found': typeof ErrorNotFoundIndexRoute
  '/services': typeof PublicServicesIndexRoute
  '/frequent-questions': typeof PublicGeneralFrequentQuestionsIndexRoute
  '/frequent-questions/companies': typeof PublicGeneralFrequentQuestionsCompaniesIndexRoute
  '/app/$companySlug': typeof AppCompanyorganizationSetCompanySlugIndexRoute
  '/app/~/settings': typeof AppCompanynoOrganizationSetChar126SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicLayoutRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInLayoutRouteWithChildren
  '/_auth/sign-up': typeof AuthSignUpLayoutRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_error/not-found/': typeof ErrorNotFoundIndexRoute
  '/_public/services/': typeof PublicServicesIndexRoute
  '/app/_company/_(organization-set)/$companySlug': typeof AppCompanyorganizationSetCompanySlugLayoutRouteWithChildren
  '/_public/_general/frequent-questions/': typeof PublicGeneralFrequentQuestionsIndexRoute
  '/_public/_general/frequent-questions/companies/': typeof PublicGeneralFrequentQuestionsCompaniesIndexRoute
  '/app/_company/_(organization-set)/$companySlug/': typeof AppCompanyorganizationSetCompanySlugIndexRoute
  '/app/_company/_(no-organization-set)/~/settings/': typeof AppCompanynoOrganizationSetChar126SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/sign-in/'
    | '/sign-up/'
    | '/not-found/'
    | '/services/'
    | '/app/$companySlug'
    | '/frequent-questions/'
    | '/frequent-questions/companies/'
    | '/app/$companySlug/'
    | '/app/~/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/not-found'
    | '/services'
    | '/frequent-questions'
    | '/frequent-questions/companies'
    | '/app/$companySlug'
    | '/app/~/settings'
  id:
    | '__root__'
    | '/_public'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_public/'
    | '/_auth/sign-in/'
    | '/_auth/sign-up/'
    | '/_error/not-found/'
    | '/_public/services/'
    | '/app/_company/_(organization-set)/$companySlug'
    | '/_public/_general/frequent-questions/'
    | '/_public/_general/frequent-questions/companies/'
    | '/app/_company/_(organization-set)/$companySlug/'
    | '/app/_company/_(no-organization-set)/~/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  AuthSignInLayoutRoute: typeof AuthSignInLayoutRouteWithChildren
  AuthSignUpLayoutRoute: typeof AuthSignUpLayoutRouteWithChildren
  ErrorNotFoundIndexRoute: typeof ErrorNotFoundIndexRoute
  AppCompanyorganizationSetCompanySlugLayoutRoute: typeof AppCompanyorganizationSetCompanySlugLayoutRouteWithChildren
  AppCompanynoOrganizationSetChar126SettingsIndexRoute: typeof AppCompanynoOrganizationSetChar126SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/services/': {
      id: '/_public/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof PublicServicesIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_error/not-found/': {
      id: '/_error/not-found/'
      path: '/not-found'
      fullPath: '/not-found/'
      preLoaderRoute: typeof ErrorNotFoundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthSignUpLayoutRoute
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthSignInLayoutRoute
    }
    '/_public/_general/frequent-questions/': {
      id: '/_public/_general/frequent-questions/'
      path: '/frequent-questions'
      fullPath: '/frequent-questions/'
      preLoaderRoute: typeof PublicGeneralFrequentQuestionsIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/app/_company/_(organization-set)/$companySlug': {
      id: '/app/_company/_(organization-set)/$companySlug'
      path: '/app/$companySlug'
      fullPath: '/app/$companySlug'
      preLoaderRoute: typeof AppCompanyorganizationSetCompanySlugLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_company/_(organization-set)/$companySlug/': {
      id: '/app/_company/_(organization-set)/$companySlug/'
      path: '/'
      fullPath: '/app/$companySlug/'
      preLoaderRoute: typeof AppCompanyorganizationSetCompanySlugIndexRouteImport
      parentRoute: typeof AppCompanyorganizationSetCompanySlugLayoutRoute
    }
    '/_public/_general/frequent-questions/companies/': {
      id: '/_public/_general/frequent-questions/companies/'
      path: '/frequent-questions/companies'
      fullPath: '/frequent-questions/companies/'
      preLoaderRoute: typeof PublicGeneralFrequentQuestionsCompaniesIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/app/_company/_(no-organization-set)/~/settings/': {
      id: '/app/_company/_(no-organization-set)/~/settings/'
      path: '/app/~/settings'
      fullPath: '/app/~/settings/'
      preLoaderRoute: typeof AppCompanynoOrganizationSetChar126SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicLayoutRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicServicesIndexRoute: typeof PublicServicesIndexRoute
  PublicGeneralFrequentQuestionsIndexRoute: typeof PublicGeneralFrequentQuestionsIndexRoute
  PublicGeneralFrequentQuestionsCompaniesIndexRoute: typeof PublicGeneralFrequentQuestionsCompaniesIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicServicesIndexRoute: PublicServicesIndexRoute,
  PublicGeneralFrequentQuestionsIndexRoute:
    PublicGeneralFrequentQuestionsIndexRoute,
  PublicGeneralFrequentQuestionsCompaniesIndexRoute:
    PublicGeneralFrequentQuestionsCompaniesIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface AuthSignInLayoutRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthSignInLayoutRouteChildren: AuthSignInLayoutRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthSignInLayoutRouteWithChildren =
  AuthSignInLayoutRoute._addFileChildren(AuthSignInLayoutRouteChildren)

interface AuthSignUpLayoutRouteChildren {
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthSignUpLayoutRouteChildren: AuthSignUpLayoutRouteChildren = {
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthSignUpLayoutRouteWithChildren =
  AuthSignUpLayoutRoute._addFileChildren(AuthSignUpLayoutRouteChildren)

interface AppCompanyorganizationSetCompanySlugLayoutRouteChildren {
  AppCompanyorganizationSetCompanySlugIndexRoute: typeof AppCompanyorganizationSetCompanySlugIndexRoute
}

const AppCompanyorganizationSetCompanySlugLayoutRouteChildren: AppCompanyorganizationSetCompanySlugLayoutRouteChildren =
  {
    AppCompanyorganizationSetCompanySlugIndexRoute:
      AppCompanyorganizationSetCompanySlugIndexRoute,
  }

const AppCompanyorganizationSetCompanySlugLayoutRouteWithChildren =
  AppCompanyorganizationSetCompanySlugLayoutRoute._addFileChildren(
    AppCompanyorganizationSetCompanySlugLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  AuthSignInLayoutRoute: AuthSignInLayoutRouteWithChildren,
  AuthSignUpLayoutRoute: AuthSignUpLayoutRouteWithChildren,
  ErrorNotFoundIndexRoute: ErrorNotFoundIndexRoute,
  AppCompanyorganizationSetCompanySlugLayoutRoute:
    AppCompanyorganizationSetCompanySlugLayoutRouteWithChildren,
  AppCompanynoOrganizationSetChar126SettingsIndexRoute:
    AppCompanynoOrganizationSetChar126SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
